### ISSUE TITLE
Ability to delete device.tracker objects in HA

### ISSUE THREAD

**Issue by PrayerfulDrop** [jrlucier/eero_tracker#26]
So I was troubleshooting my install and commented out "only_macs" section.  Immediately realized how bad of a decision that was as suddenly 89 new device.tracker entities became available.  How can I delete these as the option is greyed out.

**Comment by jrlucier** [comment]
Hi @PrayerfulDrop!  Sadly we have no control over that.  HA will auto inject all the devices into your known_devices.yaml since that's the default behavior.  You'll have to manually remove them from there.  This is true with all device_tracker integrations.  It's an HA thing, which I find a bit odd in how they handle it.

Sorry I don't have any good news!
