### ISSUE TITLE
Device nicknames not updating.

### ISSUE THREAD

**Issue by austinmeier** [jrlucier/eero_tracker#9]
Using the default configuration in `configuration.yaml`:

```
device_tracker:
  - platform: eero_tracker
    consider_home: 300
    interval_seconds: 60 
```
 The device nicknames do not update when they are changed from the eero app.  The mac addresses show just fine, and outside the names, there doesn't seem to be any issues. I have tried restarting the eero app, the modem, the eero router, and I've attempted to re-run `eero_tracker_instantiate.py`

Note: when re-running `eero_tracker_instantiate.py` the sytems obviously sees the nicknames, because they are printed out to the std.out

Seems to be something about not-updating.  Because when I first installed the eero tracker on my HA, it picked up the ONE device that I had already given a nickname in the eero app.  However, I have since changed the name of this one device, and the new nickname has not been reflected in the hassio interface.

HA version: 0.101.3

eeroOS version: 3.17.0

raspberry pi3

Let me know if you need any other details.  (thanks for this sweet add on!)

**Comment by jrlucier** [comment]
Sorry for the delay in responding to this.  So the problem tends to be more with HA than this code.

Once a device is tracked via eero_tracker, it passes that information off to HA to use.  HA will store the name given to the device in known_devices at that moment in time.  At that point the name is "fixed", and the only way to change it is to update the `known_devices.yml` in HA.  It's a one-and-done thing, and HA would have to update their system to handle name changes.  

Sadly there's not much I can do to help with this problem since it's out of our hands.  You could request that feature in HA though.  Hopefully that makes sense :)

**Comment by austinmeier** [comment]
Sorry I never followed up on this, but it ended up working once I updated, and did a full reinstall of hassOS and hassio.  So I have no idea why it wasn't working in the first place.

I do appreciate this add on, as it gives me pretty damn reliable device tracking.
